name: Windows-Desktop-Remote

on:
  workflow_dispatch:

jobs:
  windows-desktop:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Menyiapkan Chrome Remote Desktop
        shell: cmd
        run: |
          :: Bypass SSL dan unduh installer msi asli menggunakan WebClient Windows
          powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://dl.google.com/remotedesktop/headless/chromeremotedesktophost.msi', 'chromeremotedesktophost.msi')"
          
          :: Eksekusi instalasi secara diam-diam
          msiexec /i chromeremotedesktophost.msi /qn /norestart

      - name: Menghubungkan RDP Windows
        shell: cmd
        run: |
          :: Menjalankan RDP menggunakan kode otorisasi terbaru Anda (PIN default: 123456)
          "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AdkVLPyZnPItUePwgTcNMXkGLiaIp8tkVijJCrqz3mciGeSBpfTkoeOnJs6zwsGUksvBbw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME% --pin=123456

      - name: Keep Alive
        shell: cmd
        run: |
          :: Menjaga server Windows tetap aktif selama 6 jam
          powershell -Command "Start-Sleep -Seconds 21600"
          
