name: Windows-Desktop-Remote

on:
  workflow_dispatch:

jobs:
  windows-desktop:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Mengambil File MSI dari Repositori
        uses: actions/checkout@v4

      - name: Menyiapkan Chrome Remote Desktop
        shell: cmd
        run: |
          :: Menjalankan instalasi msi langsung dari file yang ada di repo Anda
          msiexec /i chromeremotedesktophost.msi /qn /norestart
          
      - name: Menghubungkan RDP Windows
        shell: cmd
        run: |
          :: Menggunakan kode otorisasi terbaru Anda (PIN default: 123456)
          "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AdkVLPyVYr761glHq73VJIH4-nTibKqhgfHgjzmdQEVz9JiBRx0nECjFuY0Da1qb9Gun2Q" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME% --pin=123456

      - name: Keep Alive
        shell: cmd
        run: |
          :: Menjaga server Windows tetap hidup selama 6 jam
          powershell -Command "Start-Sleep -Seconds 21600"
          
